# Generated by Django 5.2.17 on 2026-08-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_address", models.CharField(max_length=500)),
                ("end_address", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripHome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("visit_order", models.IntegerField()),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("zpid", models.CharField(blank=True, max_length=20, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("bedrooms", models.IntegerField(blank=True, null=True)),
                ("bathrooms", models.FloatField(blank=True, null=True)),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("photos", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homes",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["visit_order"],
            },
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["user", "-created_at"], name="trips_trip_user_id_2f4a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="triphome",
            index=models.Index(
                fields=["trip", "visit_order"], name="trips_triph_trip_id_e46e41_idx"
            ),
        ),
    ]
