# Generated by Django 5.2.17 on 2026-08-28 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_derivation_salt", models.BinaryField()),
                ("encrypted_master_key", models.BinaryField()),
                ("master_key_nonce", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_vault",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("receipts", "Receipts"),
                            ("mortgage", "Mortgage"),
                            ("offer_letter", "Offer Letter"),
                            ("inspection", "Inspection"),
                            ("appraisal", "Appraisal"),
                            ("title", "Title"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("encrypted_file_key", models.BinaryField()),
                ("storage_path", models.CharField(max_length=500)),
                ("file_size", models.IntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vault",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documents.documentvault",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("storage_path", models.CharField(max_length=500)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["vault", "-created_at"], name="documents_d_vault_i_2a843c_idx"
            ),
        ),
    ]
