# Generated by Django 5.2.17 on 2026-08-23 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login.succeeded", "Login succeeded"),
                            ("login.failed", "Login failed"),
                            ("logout", "Logout"),
                            ("password.changed", "Password changed"),
                            ("password.reset_requested", "Password reset requested"),
                            ("email.verified", "Email verified"),
                            ("account.created", "Account created"),
                            ("account.deleted", "Account deleted"),
                            ("api_key.created", "API key created"),
                            ("api_key.revoked", "API key revoked"),
                            ("member.invited", "Member invited"),
                            ("member.joined", "Member joined"),
                            ("member.removed", "Member removed"),
                            ("member.role_changed", "Member role changed"),
                            ("two_factor.enabled", "Two-factor enabled"),
                            ("two_factor.disabled", "Two-factor disabled"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "actor_label",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("target", models.CharField(blank=True, default="", max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_audit_actor_i_fb4253_idx",
                    )
                ],
            },
        ),
    ]
