# Generated by Django 5.2.17 on 2026-08-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("login.succeeded", "Login succeeded"),
                    ("login.failed", "Login failed"),
                    ("logout", "Logout"),
                    ("password.changed", "Password changed"),
                    ("password.reset_requested", "Password reset requested"),
                    ("email.verified", "Email verified"),
                    ("account.created", "Account created"),
                    ("account.deleted", "Account deleted"),
                    ("api_key.created", "API key created"),
                    ("api_key.revoked", "API key revoked"),
                    ("member.invited", "Member invited"),
                    ("member.joined", "Member joined"),
                    ("member.removed", "Member removed"),
                    ("member.role_changed", "Member role changed"),
                    ("two_factor.enabled", "Two-factor enabled"),
                    ("two_factor.disabled", "Two-factor disabled"),
                    ("mcp_client.called", "Outbound MCP server called"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
    ]
