# Generated by Django 5.2.17 on 2026-08-30 22:46

import apps.app_releases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("ios", "iOS"), ("android", "Android")],
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "minimum_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Builds older than this cannot be used at all. Leave empty for no block.",
                        max_length=32,
                        validators=[apps.app_releases.models.validate_version],
                    ),
                ),
                (
                    "recommended_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Builds older than this see a dismissible prompt. Leave empty for none.",
                        max_length=32,
                        validators=[apps.app_releases.models.validate_version],
                    ),
                ),
                (
                    "store_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="The App Store or Play listing. Without it a blocked user has nowhere to go.",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional. Replaces the default wording, in whatever language you write it.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["platform"],
            },
        ),
    ]
